2025-03-26 ERROR django.request: Internal Server Error: /api/v1/reviews/ [192.168.1.36] - ValueError: Invalid input data
2025-03-26 INFO django.request: GET /api/v1/products/ 204 OK [192.168.1.46]
2025-03-26 12:33:06,000 INFO django.request: GET /admin/dashboard/ 201 OK [192.168.1.21]
2025-03-26 12:28:26,000 django.request: GET /api/v1/auth/login/ 200 OK [192.168.1.58]
2025-03-26 12:21:05,000 ERROR django.request: Internal Server Error: /admin/dashboard/ [192.168.1.67] - OSError: No space left on device
2025-03-26 12:47:21,000 DEBUG django.db.backends: (0.33) SELECT * FROM 'dashboard' WHERE id = 67;
2025-03-26 12:19:07,000 INFO django.request: GET /admin/login/ 201 OK [192.168.1.86]
2025-03-26 12:01:43,000 WARNING django.security: DatabaseError: Deadlock detected
2025-03-26 12:25:10,000 INFO django.request: GET /api/v1/users/ 201 OK [192.168.1.61]
2025-03-26 12:49:01,000 DEBUG django.db.backends: (0.28) SELECT * FROM 'shipping' WHERE id = 29;
2025-03-26 12:12:11,000 INFO django.request: GET 201 OK [192.168.1.52]
2025-03-26 12:36:49,000 DEBUG django.db.backends: (0.23) SELECT * FROM 'dashboard' WHERE id = 3;
2025-03-26 12:24:27,000 INFO django.request: GET /api/v1/auth/login/ 200 OK [192.168.1.41]
2025-03-26 12:45:31,000 INFO django.request: GET /api/v1/reviews/ 201 OK [192.168.1.50]
2025-03-26 12:49:53,000 ERROR django.request: Internal Server Error: /api/v1/orders/ [192.168.1.64] - IntegrityError: duplicate key value violates unique constraint
2025-03-26 12:03:00,000 INFO django.request: GET /api/v1/reviews/ 204 OK [192.168.1.37]
2025-03-26 12:05:59,000 DEBUG django.db.backends: (0.6) SELECT * FROM 'payments' WHERE id = 98;
2025-03-26 12:26:58,000 INFO django.request: GET /admin/login/ 201 OK [192.168.1.81]
2025-03-26 12:35:57,000 INFO django.request: GET /api/v1/support/ 200 OK [192.168.1.47]
2025-03-26 12:45:32,000 WARNING django.security: ConnectionError: Failed to connect to payment gateway
2025-03-26 12:34:49,000 DEBUG django.db.backends: (0.32) SELECT * FROM 'support' WHERE id = 11;
2025-03-26 12:27:50,000 ERROR django.request: Internal Server Error: /api/v1/auth/login/ [192.168.1.33] - OSError: No space left on device
2025-03-26 12:12:00,000 DEBUG django.db.backends: (0.34) SELECT * FROM 'reviews' WHERE id = 74;
2025-03-26 12:35:13,000 INFO django.request: GET 201 OK [192.168.1.44]
2025-03-26 12:03:29,000 ERROR django.request: Internal Server Error: /api/v1/cart/ [192.168.1.38] - ConnectionError: Failed to connect to payment gateway
2025-03-26 12:06:17,000 DEBUG django.db.backends: (0.46) SELECT * FROM 'checkout' WHERE id = 9;
2025-03-26 12:47:31,000 INFO django.request: GET /api/v1/reviews 201 OK [192.168.1.98]
2025-03-26 12:49:39,000 DEBUG django.db.backends: (0.5) SELECT * FROM 'login' WHERE id = 82;
2025-03-26 12:19:12,000 ERROR django.request: Internal Server Error: /api/v1/users/ [192.168.1.30] - ValueError: Invalid input data
2025-03-26 12:38:06,000 DEBUG django.db.backends: (0.47) SELECT * FROM 'login' WHERE id = 83;
2025-03-26 12:35:04,000 INFO django.request: GET 204 OK [192.168.1.94]
2025-03-26 12:38:59,000 INFO django.request: GET  201 OK [192.168.1.46]
2025-03-26 12:24:59,000 INFO django.request: GET /api/v1/users/ 200 OK [192.168.1.71]
2025-03-26 12:26:39,000 INFO django.request: GET /api/v1/cart/ 204 OK [192.168.1.58]
2025-03-26 12:00:06,000 CRITICAL django.core.management: IntegrityError: duplicate key value violates unique constraint
2025-03-26 12:18:18,000 DEBUG django.db.backends: (0.2) SELECT * FROM 'cart' WHERE id = 51;
2025-03-26 12:15:21,000 INFO django.request: GET reviews/ 201 OK [192.168.1.84]
2025-03-26 12:27:06,000 ERROR django.request: Internal Server Error: /api/v1/products/ [192.168.1.43] - SuspiciousOperation: Invalid HTTP_HOST header
2025-03-26 12:44:08,000 DEBUG django.db.backends: (0.15) SELECT * FROM 'cart' WHERE id = 74;
2025-03-26 12:32:41,000 CRITICAL django.core.management: PermissionDenied: User does not have permission
2025-03-26 12:04:55,000 CRITICAL django.core.management: SuspiciousOperation: Invalid HTTP_HOST header
2025-03-26 12:01:50,000 ERROR django.request: Internal Server Error: /api/v1/support/ [192.168.1.69] - DatabaseError: Deadlock detected
2025-03-26 12:29:35,000 INFO django.request: GET /api/v1/auth/login/ 204 OK [192.168.1.44]
2025-03-26 12:37:47,000 WARNING django.security: ValueError: Invalid input data
2025-03-26 12:14:50,000 INFO django.request: GET /api/v1/products/ 201 OK [192.168.1.44]
2025-03-26 12:17:46,000 WARNING django.security: ValueError: Invalid input data
2025-03-26 12:38:41,000 DEBUG django.db.backends: (0.13) SELECT * FROM 'support' WHERE id = 19;
2025-03-26 12:38:30,000 INFO django.request: GET /api/v1/payments/ 200 OK [192.168.1.44]
2025-03-26 12:07:42,000 INFO django.request: GET /api/v1/support/ 200 OK [192.168.1.38]
